Build Step added1

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -29,6 +29,17 @@ jobs:
             sudo apt-get update
             sudo apt-get install -y protobuf-compiler  
 
+        - name: Check pb directory and demo.proto file
+          run: |
+              if [ ! -d "./src/frontend/pb" ]; then
+                echo "Error: ./src/frontend/pb directory does not exist."
+                exit 1
+              fi
+              if [ ! -f "./src/frontend/pb/demo.proto" ]; then
+                echo "Error: demo.proto file does not exist in ./src/frontend/pb directory."
+                exit 1
+              fi     
+
         - name: Build
           run: npm run build
 
